heat_template_version: 2013-05-23

description: >
  HOT template to deploy an automation server to host the REST API for 
  onboarding automation and assign a floating IP address to the server

parameters:
  key_name:
    type: string
    description: Name of keypair to assign to servers
    default: keypair
  image:
    type: string
    description: Name of image to use for servers
    default: debian-wheezy-amd64
  admin_user:
    type: string
    description: Username of admin user
    default: debian
  flavor:
    type: string
    description: Flavor to use for servers
    default: m1.medium
  public_net_id:
    type: string
    description: >
      ID of public network for which floating IP addresses will be allocated
    default: PUBNET_GUID
  private_net_id:
    type: string
    description: ID of private network into which servers get deployed
    default: PRIVNET_GUID
  private_subnet_id:
    type: string
    description: ID of private sub network into which servers get deployed
    default: SUBNET_GUID

resources:
  automation_server:
    type: OS::Nova::Server
    properties:
      name: Automation Server
      admin_user: { get_param: admin_user }
      image: { get_param: image }
      flavor: { get_param: flavor }
      key_name: { get_param: key_name }
      networks:
        - port: { get_resource: automation_server_port }

  automation_server_port:
    type: OS::Neutron::Port
    properties:
      network_id: { get_param: private_net_id }
      fixed_ips:
        - subnet_id: { get_param: private_subnet_id }
      security_groups: [{ get_resource: automation_server_security_group }]

  automation_server_floating_ip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network_id: { get_param: public_net_id }
      port_id: { get_resource: automation_server_port }

  automation_server_security_group:
    type: OS::Neutron::SecurityGroup
    properties:
      description: Add security group rules for server
      name: automation-security-group
      rules:
        - remote_ip_prefix: 0.0.0.0/0
          protocol: tcp
          port_range_min: 22
          port_range_max: 22
        - remote_ip_prefix: 0.0.0.0/0
          protocol: tcp
          port_range_min: 80
          port_range_max: 80
        - remote_ip_prefix: 0.0.0.0/0
          protocol: tcp
          port_range_min: 443
          port_range_max: 443
        - remote_ip_prefix: 0.0.0.0/0
          protocol: icmp

outputs:
  automation_private_ip:
    description: IP address of server1 in private network
    value: { get_attr: [ automation_server, first_address ] }
  automation_public_ip:
    description: Floating IP address of server1 in public network
    value: { get_attr: [ automation_server_floating_ip, floating_ip_address ] }

