---
- name: Install bottle app
  apt: pkg={{ item }} state=installed update_cache=true
  with_items:
     - uwsgi
     - uwsgi-plugin-python
     - python-pip
     - python-dev
     - libldap2-dev
     - libsasl2-dev
     - libssl-dev
     - libffi-dev

- name: Install virtualenv
  pip: name=virtualenv

- name: Install bottle and other requirements
  pip: name={{ item }} virtualenv=/usr/share/nginx/onboarding/env
  with_items:
     - bottle
     - python-ldap
     - attrdict
     - requests
     - pyjwt
     - pyopenssl
     - ndg-httpsclient
     - pyasn1

- name: Update ownership/permissions for virtualenv
  file: path=/usr/share/nginx/onboarding/env owner=www-data group=www-data recurse=yes

- name: Ensure directories
  file: path=/usr/share/nginx/onboarding state=directory mode=0750 group=www-data owner=www-data

- name: Copy configuration files into place
  template: src={{ item.src }} dest={{ item.dest }} group=www-data owner=www-data
  with_items:
     - {src: 'onboarding.ini', dest: '/etc/uwsgi/apps-available/onboarding.ini'}
     - {src: 'onboarding', dest: '/etc/nginx/sites-available/onboarding'}
  notify: restart uwsgi

- name: Link onboarding virtualhost file into sites-enabled
  file: src={{ item.src }} dest={{ item.dest }} owner=www-data group=www-data state=link
  with_items:
     - {src: '/etc/nginx/sites-available/onboarding', dest: '/etc/nginx/sites-enabled/onboarding'}
     - {src: '/etc/uwsgi/apps-available/onboarding.ini', dest: '/etc/uwsgi/apps-enabled/onboarding.ini'}
  notify: 
    - restart nginx
    - restart uwsgi

- name: Copy SSL files into place
  template: src={{ item.src }} dest={{ item.dest }} owner=root group=root
  with_items:
     - src: onboarding.hos.hpecorp.net.key
       dest: /etc/ssl/private/onboarding.hos.hpecorp.net.key
     - src: "{{ ssl_crt_filename }}"
       dest: /etc/ssl/certs/{{ ssl_crt_filename }}
  notify: 
    - restart nginx
    - restart uwsgi

- name: Copy application files into place
  copy: src={{ item.src }} dest={{ item.dest }} owner=www-data group=www-data
  with_items:
     - src: ../../../../onboarding.py
       dest: /usr/share/nginx/onboarding/onboarding.py
     - src: ../../../../automate_als.py
       dest: /usr/share/nginx/onboarding/automate_cf.py
     - src: ../../../../automate_openstack.py
       dest: /usr/share/nginx/onboarding/automate_openstack.py
     - src: ../../../../automate_ucmdb.py
       dest: /usr/share/nginx/onboarding/automate_ucmdb.py
     - src: ../../../../ucmdb.conf.json
       dest: /usr/share/nginx/onboarding/ucmdb.conf.json
  notify: restart uwsgi

- name: Copy applicaiton configuration files into place
  template: src={{ item.src }} dest={{ item.dest }} group=www-data owner=www-data
  with_items:
     - src: ../../../../als.conf.json
       dest: /usr/share/nginx/onboarding/als.conf.json
     - src: ../../../../openstack.v2.conf.json
       dest: /usr/share/nginx/onboarding/openstack.v2.conf.json
     - src: ../../../../openstack.v3.conf.json
       dest: /usr/share/nginx/onboarding/openstack.v3.conf.json
