---
- name: Install nginx
  apt: pkg=nginx state=installed update_cache=true

- name: Copy nginx configuration
  template: src=default dest=/etc/nginx/sites-available/default
  notify: restart nginx

- name: Copy index.html
  template: src=index.html dest=/usr/share/nginx/html/index.html
  notify: restart nginx

- name: Link default into sites-enabled
  file: src=/etc/nginx/sites-available/default dest=/etc/nginx/sites-enabled/default owner=www-data group=www-data state=link
  notify: restart nginx